### ISSUE TITLE
セッション情報？

### ISSUE THREAD

**Issue by nissato-hitoshi** [JapanComputerServicesInc/AspnetMVC5Template#23]
なんかいっぱい表示されるけどわざと？
セッション値が10ページぶんくらい表示されている。
※ダミーで作成したものが表示されているだけなら問題なし

**Comment by takuya3753** [comment]
それはダミーで表示しているだけです。
消してないのでそのまま残りますが（笑）

**Comment by nissato-hitoshi** [comment]
了解、それじゃ問題ありません。
何回も開いたり閉じたりしているとSESSIONが増えていくのかと思いました（笑）
