### ISSUE TITLE
実行するまでの手順がほしい。

### ISSUE THREAD

**Issue by nissato-hitoshi** [JapanComputerServicesInc/AspnetMVC5Template#8]
新規に Github からクローンしてからの手順がほしいです。

１．クローン
２．VSでソリューションを開く
３．ビルド
４．app_data 配下の ZIP を展開
５．起動

＜補足＞
　ログイン時のユーザーID,パスワードがわからないのでその情報もほしい。

**Comment by takuya3753** [comment]
とりあえず、使用方法のページ作りました。
https://github.com/JapanComputerServicesInc/AspnetMVC5Template/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

ほかに足りなそうなものがあれば、コメントしてください。

**Comment by nissato-hitoshi** [comment]
確認しました。
とりあえずこんな形で増やしていきましょう。
